import { Order, StoreSettings } from '../types';
import {
  buildExactInvoiceSvg as buildExactInvoiceSvgBase,
  svgToBrowserPngBytes,
} from './exactInvoiceTemplateBase';

export { svgToBrowserPngBytes };

const escInvoiceDistrict = (v: unknown) => String(v ?? '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

// Keep this system footer on the shared Footer style only. Per-text style IDs can
// shift when optional total rows (Qty Offer / Wrapping Cost, etc.) are present,
// which previously made this one line render at different sizes between invoices.
const normalizeGeneratedByFooter = (svg: string) => svg.replace(
  /<text\b[^>]*>Generated by O-RA Store System<\/text>/,
  '<text class="t footer" x="1482" y="1049" text-anchor="end">Generated by O-RA Store System</text>'
);

// Keep the approved Invoice V6 template untouched. Add only the requested
// District line in the unused customer-details space directly below City.
export function buildExactInvoiceSvg(
  order: Order,
  settings: StoreSettings,
  sample = false,
  pageItems?: Order['items'],
  pageIndex = 0,
  totalPages = 1,
) {
  const baseSvg = buildExactInvoiceSvgBase(order, settings, sample, pageItems, pageIndex, totalPages);
  const svg = normalizeGeneratedByFooter(baseSvg);
  const district = String((order as any)?.district || '').trim();
  if (!district) return svg;

  const marker = '<!-- Waybill: no redundant courier name -->';
  if (!svg.includes(marker)) return svg;

  // District values can contain multiple words (for example "Gampaha District").
  // Keep the complete value on one line and start it far enough to the right so it
  // can never overlap the fixed "District -" label.
  const districtLine = [
    '<text class="t label" x="650" y="350">District</text>',
    '<text class="t label" x="760" y="350">-</text>',
    `<text class="t value" x="805" y="350">${escInvoiceDistrict(district)}</text>`,
  ].join('');

  return svg.replace(marker, `${districtLine}\n\n${marker}`);
}
