import { Order, StoreSettings } from '../types';
import {
  buildExactInvoiceSvg as buildExactInvoiceSvgBase,
  svgToBrowserPngBytes,
} from './exactInvoiceTemplateBase';

export { svgToBrowserPngBytes };

const escInvoiceDistrict = (v: unknown) => String(v ?? '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

// Keep this system footer on the shared Footer style only. Per-text style IDs can
// shift when optional total rows (Qty Offer / Wrapping Cost, etc.) are present,
// which previously made this one line render at different sizes between invoices.
const normalizeGeneratedByFooter = (svg: string) => svg.replace(
  /<text\b[^>]*>Generated by O-RA Store System<\/text>/,
  '<text class="t footer" x="1482" y="1049" text-anchor="end">Generated by O-RA Store System</text>'
);

// Invoice item rows are only 54 SVG units high. Keep long saved product-name
// snapshots inside ITEM / DESCRIPTION instead of allowing them to run into QTY.
// Short names are returned byte-for-byte unchanged.
const wrapInvoiceItemDescriptions = (svg: string) => {
  const splitLines = (value: string, maxChars = 42, maxLines = 3) => {
    const words = String(value || '').trim().split(/\s+/).filter(Boolean);
    if (!words.length) return [] as string[];
    const lines: string[] = [];
    let current = '';

    for (const word of words) {
      const next = current ? `${current} ${word}` : word;
      if (next.length <= maxChars || !current) {
        current = next;
        continue;
      }
      lines.push(current);
      current = word;
      if (lines.length >= maxLines - 1) break;
    }

    if (current && lines.length < maxLines) {
      const consumed = lines.join(' ').split(/\s+/).filter(Boolean).length;
      const remaining = words.slice(consumed).join(' ');
      lines.push(remaining || current);
    }

    if (lines.length === maxLines && lines[maxLines - 1].length > maxChars) {
      const last = lines[maxLines - 1];
      lines[maxLines - 1] = `${last.slice(0, Math.max(1, maxChars - 1)).trimEnd()}…`;
    }
    return lines;
  };

  const withFontSize = (attrs: string, size: number) => {
    if (/\sstyle="[^"]*"/.test(attrs)) {
      return attrs.replace(/\sstyle="([^"]*)"/, (_m, style) => ` style="${style};font-size:${size}px"`);
    }
    return `${attrs} style="font-size:${size}px"`;
  };

  return svg.replace(
    /<text\b((?=[^>]*\bx="335")(?=[^>]*\by="(559|613|667|721)")[^>]*)>([^<]*)<\/text>/g,
    (full, attrs: string, yText: string, content: string) => {
      if (!content || content.length <= 42) return full;
      const lines = splitLines(content);
      if (lines.length <= 1) return full;

      const y = Number(yText);
      const threeLines = lines.length >= 3;
      const fontSize = threeLines ? 16 : 19;
      const lineGap = threeLines ? 16 : 19;
      const firstY = threeLines ? y - 16 : y - 9;
      const safeAttrs = withFontSize(attrs, fontSize);
      const tspans = lines
        .map((line, index) => `<tspan x="335" y="${firstY + index * lineGap}">${line}</tspan>`)
        .join('');
      return `<text${safeAttrs}>${tspans}</text>`;
    },
  );
};

// Keep the approved Invoice V6 template untouched. Add only the requested
// District line in the unused customer-details space directly below City.
export function buildExactInvoiceSvg(
  order: Order,
  settings: StoreSettings,
  sample = false,
  pageItems?: Order['items'],
  pageIndex = 0,
  totalPages = 1,
) {
  // Add District to the base SVG before its text-style/text-content pass. This keeps
  // every existing Invoice Design text ID stable and prevents a saved override from
  // being applied to the District value (the cause of the overlapping duplicate word).
  const district = String((order as any)?.district || '').trim();
  const baseOrder = district ? ({ ...(order as any), district: '' } as Order) : order;
  let svg = buildExactInvoiceSvgBase(baseOrder, settings, sample, pageItems, pageIndex, totalPages);
  svg = normalizeGeneratedByFooter(svg);
  svg = wrapInvoiceItemDescriptions(svg);
  if (!district) return svg;

  const marker = '<!-- Waybill: no redundant courier name -->';
  if (!svg.includes(marker)) return svg;

  const districtLine = [
    '<text class="t label" x="650" y="350">District</text>',
    '<text class="t label" x="760" y="350">-</text>',
    `<text class="t value" x="805" y="350">${escInvoiceDistrict(district)}</text>`,
  ].join('');

  return svg.replace(marker, `${districtLine}\n\n${marker}`);
}
