export const fardarDeliveredProfitReportPatch = () => ({
  name: 'ora-fardar-delivered-profit-report-patch',
  enforce: 'pre' as const,
  transform(code: string, rawId: string) {
    const id = rawId.split('?')[0].replace(/\\/g, '/');
    if (!id.endsWith('/src/components/admin/AdminDashboard.tsx')) return null;
    if (code.includes('chooseFardarDeliveredProfitCsv')) return null;

    let text = code;

    const functionMarker = '  const downloadStockReportCsv=()=>{';
    if (text.includes(functionMarker)) {
      const functions = [
        '  const downloadFardarDeliveredProfitPdfFromFile=async(file:File)=>{',
        "    const raw=await file.text();",
        "    const lines=String(raw||'').split(/\\r?\\n/).filter((line)=>line.trim());",
        "    if(lines.length<2){alert('CSV is empty or has no order rows.');return;}",
        '    const parseLine=(line:string)=>{',
        '      const out:string[]=[]; let cur=\'\'; let quoted=false;',
        '      for(let i=0;i<line.length;i+=1){',
        '        const ch=line[i];',
        '        if(ch===\'"\'){if(quoted&&line[i+1]===\'"\'){cur+=\'"\';i+=1;}else quoted=!quoted;}',
        "        else if(ch===','&&!quoted){out.push(cur.trim());cur='';}",
        '        else cur+=ch;',
        '      }',
        '      out.push(cur.trim());',
        "      return out.map((v)=>String(v||'').replace(/^\\uFEFF/,'').trim());",
        '    };',
        '    const rows=lines.map(parseLine);',
        "    const norm=(v:unknown)=>String(v||'').trim().toLowerCase();",
        "    const normHeader=(v:unknown)=>norm(v).replace(/[_-]+/g,' ').replace(/\\s+/g,' ');",
        "    const knownWaybills=new Set(orders.map((o)=>norm(o.waybill_number)).filter(Boolean));",
        "    const aliases=new Set(['waybill','waybill no','waybill number','waybill id','tracking','tracking no','tracking number','awb','awb no','awb number','airway bill','consignment no','consignment number']);",
        '    const header=rows[0].map(normHeader);',
        '    let waybillIndex=header.findIndex((h)=>aliases.has(h));',
        '    if(waybillIndex<0){',
        '      let bestIndex=-1; let bestScore=0;',
        '      const width=Math.max(...rows.map((r)=>r.length));',
        '      for(let col=0;col<width;col+=1){',
        '        const score=rows.slice(1).reduce((sum,row)=>sum+(knownWaybills.has(norm(row[col]))?1:0),0);',
        '        if(score>bestScore){bestScore=score;bestIndex=col;}',
        '      }',
        '      if(bestScore>0)waybillIndex=bestIndex;',
        '    }',
        "    if(waybillIndex<0){alert('Waybill column could not be identified in this CSV.');return;}",
        '    const csvWaybills=new Set(rows.slice(1).map((r)=>norm(r[waybillIndex])).filter(Boolean));',
        "    const reportOrders=orders.filter((o)=>csvWaybills.has(norm(o.waybill_number))&&o.order_status!=='Cancelled'&&!o.is_duplicate_order&&!o.is_test_order);",
        "    if(!reportOrders.length){alert('No system orders matched the waybills in this CSV.');return;}",
        '',
        "    const dateKey=(value:unknown)=>{const s=String(value||'').trim();const m=s.match(/^(\\d{4}-\\d{2}-\\d{2})/);if(m)return m[1];const d=new Date(s);if(Number.isNaN(d.getTime()))return '';return d.toISOString().slice(0,10);};",
        "    const reportDates=reportOrders.map((o)=>dateKey(o.fardar_tracking_updated_at||o.dispatch_scanned_at||o.created_at)).filter(Boolean).sort();",
        "    const startDate=reportDates[0]||''; const endDate=reportDates[reportDates.length-1]||startDate;",
        '',
        '    let packingExpenses:any[]=[];',
        '    try{',
        "      const token=localStorage.getItem('ora_staff_session_token')||'';",
        "      const response=await fetch('/api/admin/packing-expenses',{headers:token?{Authorization:'Bearer '+token}:{},cache:'no-store'});",
        '      const data=await response.json().catch(()=>({}));',
        '      if(response.ok&&Array.isArray(data?.expenses))packingExpenses=data.expenses;',
        '    }catch{}',
        "    const includedPacking=packingExpenses.filter((row)=>{const d=String(row?.expense_date||'').slice(0,10);if(!d)return false;if(startDate&&d<startDate)return false;if(endDate&&d>endDate)return false;return true;});",
        '    const packingMaterialCost=includedPacking.reduce((sum,row)=>sum+Math.max(0,Number(row?.total_cost||0)),0);',
        '',
        "    const grouped=new Map<string,{sku:string;name:string;qty:number;sales:number;purchaseCost:number;grossProfit:number}>();",
        '    let totalItemSales=0; let totalItemPurchaseCost=0;',
        '    reportOrders.forEach((order)=>{',
        '      (order.items||[]).forEach((item)=>{',
        "        const sku=String(item.sku||item.main_sku||'').trim().toUpperCase()||'NO-CODE';",
        '        const qty=Math.max(1,Number(item.quantity||1));',
        '        const sales=Math.max(0,Number(item.unit_price||0))*qty;',
        '        const unitPurchase=Math.max(0,Number(item.effective_buying_price??item.buying_price??0));',
        '        const purchaseCost=unitPurchase*qty;',
        "        const current=grouped.get(sku)||{sku,name:String(item.product_name||sku),qty:0,sales:0,purchaseCost:0,grossProfit:0};",
        '        current.qty+=qty; current.sales+=sales; current.purchaseCost+=purchaseCost; current.grossProfit+=sales-purchaseCost; grouped.set(sku,current);',
        '        totalItemSales+=sales; totalItemPurchaseCost+=purchaseCost;',
        '      });',
        '    });',
        "    const itemRows=Array.from(grouped.values()).sort((a,b)=>a.sku.localeCompare(b.sku,undefined,{numeric:true,sensitivity:'base'}));",
        '    const totalCollected=reportOrders.reduce((sum,o)=>sum+Math.max(0,Number(o.total_amount||0)),0);',
        '    const customerDeliveryCollected=reportOrders.reduce((sum,o)=>sum+Math.max(0,Number(o.delivery_fee||0)),0);',
        '    const totalDeliveryCost=reportOrders.reduce((sum,o)=>sum+Math.max(0,Number(o.internal_delivery_fee??o.delivery_fee??settings.delivery_fee??0)),0);',
        '    const totalCost=totalItemPurchaseCost+totalDeliveryCost+packingMaterialCost;',
        '    const netProfit=totalCollected-totalCost;',
        '',
        "    const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});",
        '    const money=(n:number)=>Math.round(Number(n||0)).toLocaleString();',
        '    let y=14;',
        "    doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('O-RA STORE - FARDAR DELIVERED ORDERS PROFIT REPORT',14,y);",
        "    y+=6;doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('Source CSV: '+file.name,14,y);",
        "    y+=4;doc.text('Matched orders: '+reportOrders.length+' | Report period: '+(startDate||'-')+' to '+(endDate||'-'),14,y);",
        '    y+=8;',
        "    doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('FINANCIAL SUMMARY',14,y);y+=6;",
        "    const summaryRows=[['Collected Revenue','Rs. '+money(totalCollected)],['Item Sales (before delivery)','Rs. '+money(totalItemSales)],['Customer Delivery Collected','Rs. '+money(customerDeliveryCollected)],['Item Purchase Cost','Rs. '+money(totalItemPurchaseCost)],['Delivery Cost','Rs. '+money(totalDeliveryCost)],['Packing Material Expense','Rs. '+money(packingMaterialCost)],['TOTAL COST','Rs. '+money(totalCost)],['NET PROFIT','Rs. '+money(netProfit)]];",
        "    doc.setFont('helvetica','normal');doc.setFontSize(8);summaryRows.forEach((row)=>{doc.text(row[0],18,y);doc.text(row[1],100,y,{align:'right'});y+=5;});",
        "    y+=3;doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('Formula: Net Profit = Collected Revenue - Item Purchase Cost - Delivery Cost - Packing Material Expense',14,y);",
        '    y+=10;',
        '',
        "    doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('ITEM CODE PURCHASE COST & GROSS PROFIT',14,y);y+=6;",
        "    const itemCols=[['Code',14],['Item',38],['Qty',145],['Item Sales',170],['Purchase Cost',215],['Gross Profit',263]] as Array<[string,number]>;",
        "    const drawItemHeader=()=>{doc.setFont('helvetica','bold');doc.setFontSize(8);itemCols.forEach(([label,x])=>doc.text(label,x,y));y+=2;doc.line(14,y,287,y);y+=5;};drawItemHeader();",
        '    itemRows.forEach((row)=>{',
        '      if(y>193){doc.addPage();y=14;drawItemHeader();}',
        "      const itemName=row.name.length>48?row.name.slice(0,45)+'...':row.name;",
        "      doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text(row.sku,14,y);doc.text(itemName,38,y);doc.text(String(row.qty),151,y,{align:'right'});doc.text('Rs. '+money(row.sales),204,y,{align:'right'});doc.text('Rs. '+money(row.purchaseCost),250,y,{align:'right'});doc.text('Rs. '+money(row.grossProfit),287,y,{align:'right'});y+=6;",
        '    });',
        '',
        '    if(y>165){doc.addPage();y=14;}else y+=6;',
        "    doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('DELIVERY COST BY WAYBILL',14,y);y+=6;",
        "    const deliveryCols=[['Order',14],['Waybill',55],['Customer',96],['Collected',190],['Delivery Cost',245]] as Array<[string,number]>;",
        "    const drawDeliveryHeader=()=>{doc.setFont('helvetica','bold');doc.setFontSize(8);deliveryCols.forEach(([label,x])=>doc.text(label,x,y));y+=2;doc.line(14,y,287,y);y+=5;};drawDeliveryHeader();",
        '    reportOrders.forEach((order)=>{',
        '      if(y>193){doc.addPage();y=14;drawDeliveryHeader();}',
        "      const customer=String(order.customer_name||'').length>38?String(order.customer_name).slice(0,35)+'...':String(order.customer_name||'');",
        '      const delivery=Math.max(0,Number(order.internal_delivery_fee??order.delivery_fee??settings.delivery_fee??0));',
        "      doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.text(String(order.order_number||''),14,y);doc.text(String(order.waybill_number||''),55,y);doc.text(customer,96,y);doc.text('Rs. '+money(order.total_amount||0),222,y,{align:'right'});doc.text('Rs. '+money(delivery),287,y,{align:'right'});y+=6;",
        '    });',
        '',
        '    if(y>165){doc.addPage();y=14;}else y+=6;',
        "    doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('PACKING MATERIAL EXPENSE INCLUDED',14,y);y+=6;",
        "    doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text('Included by expense date inside the report period above.',14,y);y+=5;",
        '    if(!includedPacking.length){doc.text(\'No packing material expense entries found for this report period.\',14,y);y+=5;}',
        '    else includedPacking.forEach((row)=>{',
        '      if(y>193){doc.addPage();y=14;}',
        "      const material=String(row.material_name||'Packing Material');",
        "      doc.text(String(row.expense_date||''),14,y);doc.text(material.length>70?material.slice(0,67)+'...':material,48,y);doc.text('Rs. '+money(row.total_cost||0),287,y,{align:'right'});y+=5;",
        '    });',
        "    y+=4;doc.setFont('helvetica','bold');doc.text('Packing Material Total: Rs. '+money(packingMaterialCost),14,y);",
        "    doc.save('O-RA_Fardar_Delivered_Profit_'+new Date().toISOString().slice(0,10)+'.pdf');",
        '  };',
        '',
        '  const chooseFardarDeliveredProfitCsv=()=>{',
        "    const picker=document.createElement('input');",
        "    picker.type='file';picker.accept='.csv,text/csv';",
        '    picker.onchange=()=>{const file=picker.files?.[0];if(file)void downloadFardarDeliveredProfitPdfFromFile(file);};',
        '    picker.click();',
        '  };',
        '',
        functionMarker,
      ].join('\n');
      text = text.replace(functionMarker, functions);
    }

    const buttonMarker = [
      '                <button type="button" onClick={downloadPackedProfitPdf} className="inline-flex items-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-[10px] font-black text-emerald-300 hover:bg-emerald-500/20">',
      '                  <FileText className="h-3.5 w-3.5"/> Packed Profit PDF',
      '                </button>',
    ].join('\n');
    if (text.includes(buttonMarker)) {
      const buttonBlock = [
        buttonMarker,
        '                <button type="button" onClick={chooseFardarDeliveredProfitCsv} className="inline-flex items-center gap-2 rounded-xl border border-violet-500/30 bg-violet-500/10 px-3 py-2 text-[10px] font-black text-violet-300 hover:bg-violet-500/20">',
        '                  <FileText className="h-3.5 w-3.5"/> Fardar Delivered CSV → Profit PDF',
        '                </button>',
      ].join('\n');
      text = text.replace(buttonMarker, buttonBlock);
    }

    return text === code ? null : { code: text, map: null };
  },
});
