import React, { useEffect, useMemo, useState } from 'react';
import { ExternalLink, Lightbulb, RefreshCw, Trash2 } from 'lucide-react';
import type { ProductRequest, ProductRequestStatus } from '../../types';

const sessionToken=()=>localStorage.getItem('ora_staff_session_token')||'';
const authHeaders=()=>({'Content-Type':'application/json',Authorization:`Bearer ${sessionToken()}`});
const statuses:ProductRequestStatus[]=['New','Reviewed','Planned','Added','Rejected'];
const keyOf=(value:string)=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9\u0D80-\u0DFF]+/g,' ').replace(/\s+/g,' ').trim();

export const ProductRequestsPanel:React.FC=()=>{
 const [requests,setRequests]=useState<ProductRequest[]>([]);const [message,setMessage]=useState('');const[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/admin/product-requests',{headers:authHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'Could not load requests.');setRequests(Array.isArray(d?.requests)?d.requests:[])}catch(e:any){setMessage(e?.message||'Could not load requests.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const demand=useMemo(()=>{const m=new Map<string,{name:string,count:number,latest:string}>();requests.filter((r)=>r.status!=='Rejected').forEach((r)=>{const k=keyOf(r.product_name);const x=m.get(k)||{name:r.product_name,count:0,latest:r.created_at};x.count+=1;if(new Date(r.created_at)>new Date(x.latest)){x.latest=r.created_at;x.name=r.product_name}m.set(k,x)});return[...m.values()].sort((a,b)=>b.count-a.count)},[requests]);
 const update=async(id:string,status:ProductRequestStatus)=>{try{const r=await fetch(`/api/admin/product-requests/${encodeURIComponent(id)}`,{method:'PATCH',headers:authHeaders(),body:JSON.stringify({status})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'Update failed.');setRequests((p)=>p.map((x)=>x.id===id?{...x,status}:x))}catch(e:any){setMessage(e?.message||'Update failed.')}};
 const remove=async(id:string)=>{if(!window.confirm('Delete this product suggestion?'))return;try{const r=await fetch(`/api/admin/product-requests/${encodeURIComponent(id)}`,{method:'DELETE',headers:authHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'Delete failed.');setRequests((p)=>p.filter((x)=>x.id!==id))}catch(e:any){setMessage(e?.message||'Delete failed.')}};
 return <div className="space-y-4"><div className="rounded-2xl bg-white border border-gray-100 p-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Lightbulb className="w-5 h-5 text-orange-600"/><div><h2 className="font-black">New Product Demand</h2><p className="text-xs text-gray-500">Customer suggestions are market-demand ideas only — they never become orders automatically.</p></div></div><button onClick={load} className="p-2 rounded-xl border border-gray-200"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div>{message&&<p className="rounded-xl bg-orange-50 border border-orange-100 p-3 text-xs font-semibold text-orange-800">{message}</p>}
 <div className="rounded-2xl bg-white border border-gray-100 p-4"><h3 className="font-black text-sm mb-3">Most Requested Ideas</h3><div className="flex flex-wrap gap-2">{demand.slice(0,20).map((d)=><span key={keyOf(d.name)} className="rounded-full bg-orange-50 border border-orange-100 px-3 py-1.5 text-xs font-bold text-orange-800">{d.name} • {d.count} request{d.count!==1?'s':''}</span>)}{demand.length===0&&<span className="text-xs text-gray-400">No suggestions yet.</span>}</div></div>
 <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">{requests.slice().sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).map((r)=><article key={r.id} className="rounded-2xl bg-white border border-gray-100 p-4 space-y-3"><div className="flex items-start justify-between gap-2"><div><p className="font-black text-sm">{r.product_name}</p><p className="text-[11px] text-gray-400">{new Date(r.created_at).toLocaleString()} • Demand group: {demand.find((d)=>keyOf(d.name)===keyOf(r.product_name))?.count||1}</p></div><select value={r.status} onChange={(e)=>update(r.id,e.target.value as ProductRequestStatus)} className="rounded-lg border border-gray-200 px-2 py-1 text-[11px] font-bold">{statuses.map((s)=><option key={s}>{s}</option>)}</select></div>{r.description&&<p className="text-xs leading-5 text-gray-600 whitespace-pre-wrap">{r.description}</p>}{r.reference_image_url&&<img src={r.reference_image_url} alt="Reference" className="w-full max-h-52 object-cover rounded-xl border border-gray-100"/>}<div className="flex flex-wrap gap-3 text-xs text-gray-500">{r.expected_price&&<span>Expected: Rs. {Number(r.expected_price).toLocaleString()}</span>}{r.customer_name&&<span>From: {r.customer_name}</span>}{r.contact&&<span>Contact: {r.contact}</span>}{r.product_link&&<a href={r.product_link} target="_blank" rel="noreferrer" className="text-orange-600 font-bold inline-flex items-center gap-1">Reference <ExternalLink className="w-3 h-3"/></a>}</div><button onClick={()=>remove(r.id)} className="text-xs font-bold text-red-600 inline-flex items-center gap-1"><Trash2 className="w-4 h-4"/>Delete</button></article>)}</div></div>;
};
