import fs from 'node:fs';
import { loadConfigFromFile } from 'vite';

// Keep the server's Sheet import on the same variant, bundle, historical-price,
// discount and invoice-snapshot rules as the production Confirm CSV importer.
// The generated module performs no browser reads or writes and no persistence.
const config = (await loadConfigFromFile({command:'build',mode:'production'}))!.config as any;
let source = fs.readFileSync('src/context/StoreContext.tsx','utf8');
for (const plugin of config.plugins.flat(Infinity)) {
  if (plugin?.name?.startsWith('ora-') && typeof plugin.transform === 'function') {
    const result = await plugin.transform(source,'/repo/src/context/StoreContext.tsx');
    if (result) source = typeof result === 'string' ? result : result.code;
  }
}
const from = source.indexOf('  const importConfirmedOrdersCsv = async');
const to = source.indexOf('  const importWebsiteConfirmedCsv',from);
if (from < 0 || to < from) throw new Error('Confirm CSV importer was not found.');
let plan = source.slice(from,to);
const replace = (from:string,to:string) => {
  if (!plan.includes(from)) throw new Error('Confirm planner marker missing: '+from.slice(0,90));
  plan = plan.replace(from,to);
};
plan = plan.slice(plan.indexOf('=> {')+4);
const persistence = plan.indexOf('    const savedDecisions=await saveConfirmCsvDecisions');
if (persistence < 0) throw new Error('Confirm persistence marker missing.');
plan = plan.slice(0,persistence);
const parseLine = plan.match(/^    const parse=.+$/m)?.[0];
const linesLine = plan.match(/^    const lines=.+$/m)?.[0];
if (!parseLine || !linesLine) throw new Error('Confirm CSV parser markers missing.');
replace(parseLine,'    const parse=(row:string[])=>row.map(value=>String(value ?? "").trim());');
replace(linesLine,'    const lines=matrix.filter(row=>row.some(value=>String(value ?? "").trim()));');
const lookupStart = plan.indexOf('    // CONFIRM UPLOAD DURABLE ORDER LOOKUP');
const lookupEnd = plan.indexOf('    const now=new Date().toISOString();',lookupStart);
if (lookupStart < 0 || lookupEnd < lookupStart) throw new Error('Durable lookup markers missing.');
plan = plan.slice(0,lookupStart) +
  '    const existing=new Map(orders.map(o=>[String(o.order_number||"").toUpperCase(),o] as [string,Order]));\n' +
  plan.slice(lookupEnd);
replace('const now=new Date().toISOString();','const now=at;');
plan = plan.replace(/return\{confirmedCount:0,/g,'return{entries:[],confirmedCount:0,');
const rateFrom = source.indexOf('  const getMultiBuyDiscountRate =');
const rateTo = source.indexOf('\n  };',rateFrom)+6;
if (rateFrom < 0 || rateTo < rateFrom) throw new Error('Quantity discount rule missing.');
const rate = source.slice(rateFrom,rateTo);
const output = `// Generated by tools/generate-confirm-sheet-plan.ts. Run it after changing CSV rules.\n`+
  `import type { Order, OrderSource, Product, StoreSettings, PaymentMethod } from '../types';\n`+
  `import { canonicalJson, type ConfirmCsvEntry } from './confirmCsvSave';\n`+
  `import { findProductSelection, normalizedProductType, buildOrderItemSnapshot } from './productVariants';\n\n`+
  `export function planConfirmSheetDecisions(matrix:string[][],orders:Order[],products:Product[],settings:StoreSettings,packingBatchId:string,at:string) {\n`+
  `  const source:OrderSource|undefined=undefined;\n  const paymentMode:'normal'|'full_paid'|'advance_50'='normal' as any;\n`+
  rate + '\n' + plan +
  `    return {entries:entries as ConfirmCsvEntry[],errors,orderNumbers,notFoundCount,ignoredCount};\n}\n`;
const path = 'src/lib/confirmSheetPlan.ts';
if (process.argv.includes('--check')) {
  if (fs.readFileSync(path,'utf8') !== output) throw new Error('Sheet planner is stale. Run tools/generate-confirm-sheet-plan.ts.');
} else fs.writeFileSync(path,output);
console.log(process.argv.includes('--check')?'PASS: Sheet and Confirm CSV rules are in sync.':'Generated the shared Sheet decision planner.');
